[package]
name = "shim-win"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Windows implementations of the shim platform traits."

[dependencies]
shim-core = { path = "../core" }
tracing.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_Foundation", "Win32_Security_WinTrust", "Win32_Security_Cryptography", "Win32_System_Memory", "Win32_Security_Cryptography_Catalog", "Win32_Security_Cryptography_Sip", "Win32_UI_Shell", "Win32_UI_WindowsAndMessaging"] }
winreg = "0.56"

[dev-dependencies]
tempfile = "3.27.0"
